# Generated by Django 2.1.2 on 2019-02-27 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=900, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=900, null=True)),
                ('logo', models.CharField(max_length=900, null=True)),
                ('contact', models.CharField(max_length=900, null=True)),
                ('email', models.CharField(max_length=900, null=True)),
                ('code', models.CharField(max_length=900, null=True)),
                ('token', models.CharField(max_length=900, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1500, null=True)),
                ('question_type', models.CharField(choices=[('OBJECTIVE', 'Objective'), ('FILL_UP', 'Fill Up'), ('CODE', 'Code'), ('CHECK_BOX', 'Check Box')], default='FILL_UP', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('question_arr', models.CharField(max_length=900, null=True)),
                ('time_limit', models.IntegerField(null=True)),
                ('identifier', models.CharField(max_length=900, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_portal.College')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.Question'),
        ),
    ]
