# Generated by Django 2.1.2 on 2019-02-27 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=900, null=True)),
                ('reg_no', models.CharField(max_length=900, null=True)),
                ('department', models.CharField(max_length=900, null=True)),
                ('college_name', models.CharField(max_length=900, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=20, null=True)),
                ('email', models.CharField(max_length=900, null=True)),
                ('phone', models.CharField(max_length=900, null=True)),
                ('dob', models.DateField(null=True)),
                ('website', models.CharField(max_length=900, null=True)),
                ('github_url', models.CharField(max_length=900, null=True)),
                ('resume', models.CharField(max_length=900, null=True)),
                ('token', models.CharField(max_length=900, null=True)),
                ('exam_started_at', models.DateTimeField(null=True)),
                ('last_submitted_at', models.DateTimeField(null=True)),
                ('time_left', models.FloatField(null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.College')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=900, null=True)),
                ('submitted_at', models.DateTimeField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.Question')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.QuestionSet')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Student')),
            ],
        ),
    ]
